### ISSUE TITLE
Add a pyppeteer based spider ?

### ISSUE THREAD

**Issue by m-yakovenko** [lewoudar/scalpel#6]
Hi, @lewoudar . Will you plan to add (or accept a PR with) a spider based on [pyppeteer](https://github.com/pyppeteer/pyppeteer) ?

**Comment by lewoudar** [comment]
Hi @m-yakovenko , first of all thanks for your interest in this project.
`pyppeteer` seems to be a good project but I don't think I want to support it. My project wants to work on both asyncio and trio, and this is possible thanks to [anyio](https://anyio.readthedocs.io/en/stable/). Unfortunately pyppeteer is based on **asyncio** not **anyio**, so support for **trio** will be tedious.

**Comment by lewoudar** [comment]
Hi @m-yakovenko , first of all thanks for your interest in this project.
`pyppeteer` seems to be a good project but I don't think I want to support it. My project wants to work on both asyncio and trio, and this is possible thanks to [anyio](https://anyio.readthedocs.io/en/stable/). Unfortunately pyppeteer is based on **asyncio** not **anyio**, so support for **trio** will be tedious.
